### ISSUE TITLE
bug parsing .jtr file

### ISSUE THREAD

**Issue by cerisara** [synalp/jtrans#32]
when parsing a .jtr file that has just been generated by jtrans, I got:

java.lang.ClassCastException: java.util.ArrayList cannot be cast to fr.loria.synalp.jtrans.project.Phrase
    at fr.loria.synalp.jtrans.gui.table.TrackModel$LinearBridge.<init>(TrackModel.java:140)
    at fr.loria.synalp.jtrans.gui.table.TrackModel.populateRows(TrackModel.java:93)
    at fr.loria.synalp.jtrans.gui.table.TrackModel.<init>(TrackModel.java:86)
    at fr.loria.synalp.jtrans.gui.table.ProjectTable.refreshModel(ProjectTable.java:171)
    at fr.loria.synalp.jtrans.gui.table.ProjectTable.<init>(ProjectTable.java:50)
    at fr.loria.synalp.jtrans.gui.JTransGUI.initPanel(JTransGUI.java:251)
    at fr.loria.synalp.jtrans.gui.JTransGUI.setProject(JTransGUI.java:495)
    at fr.loria.synalp.jtrans.gui.JTransGUI.friendlyLoadMarkup(JTransGUI.java:358)
    at fr.loria.synalp.jtrans.gui.JTransGUI.<init>(JTransGUI.java:223)
    at fr.loria.synalp.jtrans.JTrans.main(JTrans.java:412)

**Comment by cerisara** [comment]
This bug might cause other problems: for instance, I just noted that deserializing a TurnProject from a JTR file
creates null pointers to TurnProject from the inner class Turn objects;
so this creates a NullPointerException when calling inferAnchors() for instance.
